name: dispatcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.0
  - pip
  - pip:
    - streamlit==1.28.1
    - opencv-python==4.8.1.78
    - pyzbar==0.1.9
    - streamlit-webrtc==0.47.1
    - pyttsx3==2.90